/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

import com.structures.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class OperacionesLibro extends javax.swing.JFrame {

    AVLTree categoria_libro;
    ReadJson carga_m_libros;
    User actual_user;
    WindowMain wm;
    private boolean flagedit;

    /**
     * Creates new form OperacionesLibro
     *
     * @param categoria_libro
     * @param wm
     */
    public OperacionesLibro(AVLTree categoria_libro, WindowMain wm) {
        this.categoria_libro = categoria_libro;
        this.wm = wm;
        actual_user = wm.login.active_user;
        initComponents();
        txtUsuario_agrega.setText(actual_user.getNombre());
        llenarTabla_no_vacio();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        disbleTxt();
        flagedit = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusqueda = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnCarcaLibro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEdicion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdioma = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUsuario_agrega = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCrearLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("BUSCAR");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        tblBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Nombre"
            }
        ));
        tblBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusquedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusqueda);
        if (tblBusqueda.getColumnModel().getColumnCount() > 0) {
            tblBusqueda.getColumnModel().getColumn(0).setMinWidth(30);
            tblBusqueda.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblBusqueda.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel11.setText("Buscar por nombre");

        btnCarcaLibro.setText("CARGAR LIBROS");
        btnCarcaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarcaLibroActionPerformed(evt);
            }
        });

        jLabel7.setText("Libro");

        txtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtISBNKeyTyped(evt);
            }
        });

        jLabel1.setText("ISBN");

        jLabel2.setText("Titulo");

        jLabel3.setText("Autor");

        jLabel4.setText("Editorial");

        jLabel5.setText("Año");

        jLabel6.setText("Edicion");

        jLabel8.setText("Categoria");

        jLabel9.setText("Idioma");

        jLabel10.setText("Usuario");

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardarCambios.setText("GUARDAR");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCrearLibro.setText("CREAR LIBRO");
        btnCrearLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(38, 38, 38)
                        .addComponent(btnGuardarCambios)
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEditorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEdicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdioma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsuario_agrega, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnCrearLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarcaLibro)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(57, 57, 57))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtUsuario_agrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnGuardarCambios)
                            .addComponent(btnEditar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearLibro)
                            .addComponent(btnCarcaLibro))))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        wm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnCrearLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLibroActionPerformed
        NewBook nb = new NewBook(this, actual_user, categoria_libro);
        nb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearLibroActionPerformed

    private void btnCarcaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarcaLibroActionPerformed
        carga_m_libros = new ReadJson(wm.table_user, actual_user, categoria_libro);
        File f;
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        file.addChoosableFileFilter(new FileNameExtensionFilter("Archivo tipo json", "json"));
        file.setAcceptAllFileFilterUsed(true);
        int option = file.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            f = file.getSelectedFile();
            String path = file.getSelectedFile().getPath();
            carga_m_libros.readJsonBook(path);
            JOptionPane.showMessageDialog(null, "Carga Existosa!");
            fill_table();
        }

    }//GEN-LAST:event_btnCarcaLibroActionPerformed

    private void txtISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISBNKeyTyped
        if ((int) evt.getKeyChar() > 31 && (int) evt.getKeyChar() < 48 || (int) evt.getKeyChar() > 57 && (int) evt.getKeyChar() <= 255) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten números");
        }
    }//GEN-LAST:event_txtISBNKeyTyped

    private void tblBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusquedaMouseClicked
        int isbn = (int) tblBusqueda.getValueAt(tblBusqueda.getSelectedRow(), 0);
        LinkedList<BooksCategory> lista_categoria = categoria_libro.in_orden();
        for (int i = 0; i < lista_categoria.getSize(); i++) {
            BooksCategory temp = lista_categoria.getData();
 //           jcomboCategoria.addItem(temp.getName_category());
            LinkedList<Book> lstempbook = temp.getCategory().listaLibros();
            for (int j = 0; j < lstempbook.getSize(); j++) {
                Book tempbr = lstempbook.getData();
                if (tempbr.getISBN() == isbn) {
                    txtAnio.setText(tempbr.getYear() + "");
                    txtAutor.setText(tempbr.getAutor());
                    txtCategoria.setText(tempbr.getCategoria());
                    txtEdicion.setText(tempbr.getEdicion() + "");
                    txtEditorial.setText(tempbr.getEditorial());
                    txtISBN.setText(tempbr.getISBN() + "");
                    txtIdioma.setText(tempbr.getIdioma());
                    txtUsuario_agrega.setText(tempbr.getCarne_usuario_que_agrega() + "");
                    txtTitulo.setText(tempbr.getTitulo());
                }
            }
        }
    }//GEN-LAST:event_tblBusquedaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (noEmptytxt()) {
            int key = Integer.parseInt(txtISBN.getText());
            if (categoria_libro.search(txtCategoria.getText()).getCategory().search(key).getCarne_usuario_que_agrega() == actual_user.getNumero_carne()) {
                enableTxt();
                flagedit = true;
            } else {
                JOptionPane.showMessageDialog(null, "No puedes modificar el libro no te pertenece!!");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        if (noEmptytxt()) {
            if (categoria_libro.search(txtCategoria.getText()) != null && flagedit == true) {
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setAutor(txtAutor.getText());
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setCarne_usuario_que_agrega(actual_user.getNumero_carne());
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setCategoria(txtCategoria.getText());
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setEdicion(Integer.parseInt(txtEdicion.getText()));
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setEditorial(txtEditorial.getText());
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setISBN(Integer.parseInt(txtISBN.getText()));
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setIdioma(txtIdioma.getText());
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setTitulo(txtTitulo.getText());
                categoria_libro.search(txtCategoria.getText()).getCategory().search(Integer.parseInt(txtISBN.getText())).setYear(Integer.parseInt(txtAnio.getText()));
                fill_table();
                flagedit = false;
                clearTXT();
                disbleTxt();
                JOptionPane.showConfirmDialog(null, "Cambio Guardado!");
            }
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (noEmptytxt()) {
            int key = Integer.parseInt(txtISBN.getText());
            if (categoria_libro.search(txtCategoria.getText()).getCategory().search(key).getCarne_usuario_que_agrega() == actual_user.getNumero_carne()) {
                int option = JOptionPane.showConfirmDialog(null, "Eliminar el libro: " + txtTitulo.getText());
                if (option == 0) {
                    categoria_libro.search(txtCategoria.getText()).getCategory().remove(key);
                    clearTXT();
                    fill_table();
                }
            } else {
                JOptionPane.showMessageDialog(null, "No puedes modificar el libro no te pertenece!!");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        if (!"".equals(txtBuscar.getText())) {
            fillTablefilter(txtBuscar.getText());
        }else
            fill_table();
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void clearTXT() {
        txtAnio.setText("");
        txtAutor.setText("");
        txtCategoria.setText("");
        txtEdicion.setText("");
        txtEditorial.setText("");
        txtISBN.setText("");
        txtIdioma.setText("");
        txtIdioma.setText("");
        txtUsuario_agrega.setText("");
        txtTitulo.setText("");
    }

    //no tiene que haber ningun campo vacio
    private boolean noEmptytxt() {
        if (!"".equals(txtAnio.getText()) && !"".equals(txtAutor.getText())
                && !"".equals(txtCategoria.getText()) && !"".equals(txtEdicion.getText())
                && !"".equals(txtEditorial.getText()) && !"".equals(txtISBN.getText())
                && !"".equals(txtIdioma.getText()) && !"".equals(txtTitulo.getText())
                && !"".equals(txtUsuario_agrega.getText())) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "No se puede dejar campos vacios!");
            return false;
        }
    }

    //metodo para llenar la tabla
    private void fill_table() {
        DefaultTableModel tabla = (DefaultTableModel) tblBusqueda.getModel();
        tabla.setRowCount(0);
        LinkedList<BooksCategory> lista_categoria = categoria_libro.in_orden();
        for (int i = 0; i < lista_categoria.getSize(); i++) {
            BooksCategory temp = lista_categoria.getData();
//            jcomboCategoria.addItem(temp.getName_category());
            LinkedList<Book> lstempbook = temp.getCategory().listaLibros();
            for (int j = 0; j < lstempbook.getSize(); j++) {
                Book tempbr = lstempbook.getData();
                if (tempbr.getCarne_usuario_que_agrega() == actual_user.getNumero_carne()) {
                    Object[] tbl = {tempbr.getISBN(),
                        tempbr.getTitulo()
                    };
                    tabla.addRow(tbl);
                }
            }
        }
    }

    private void llenarTabla_no_vacio() {
        if (!categoria_libro.isEmpty()) {
            fill_table();
        }

    }

    private void disbleTxt() {
        txtAnio.setEditable(false);
        txtAutor.setEditable(false);
        txtCategoria.setEditable(false);
        txtEdicion.setEditable(false);
        txtEditorial.setEditable(false);
        txtISBN.setEditable(false);
        txtIdioma.setEditable(false);
        txtIdioma.setEditable(false);
        txtUsuario_agrega.setEditable(false);
        txtTitulo.setEditable(false);
    }

    private void enableTxt() {
        txtAnio.setEditable(true);
        txtAutor.setEditable(true);
        txtCategoria.setEditable(true);
        txtEdicion.setEditable(true);
        txtEditorial.setEditable(true);
        txtISBN.setEditable(true);
        txtIdioma.setEditable(true);
        txtIdioma.setEditable(true);
        txtUsuario_agrega.setEditable(true);
        txtTitulo.setEditable(true);
    }

    private void fillTablefilter(String keytyped) {
        DefaultTableModel tabla = (DefaultTableModel) tblBusqueda.getModel();
        tabla.setRowCount(0);
        LinkedList<BooksCategory> lista_categoria = categoria_libro.in_orden();
        for (int i = 0; i < lista_categoria.getSize(); i++) {
            BooksCategory temp = lista_categoria.getData();
//            jcomboCategoria.addItem(temp.getName_category());
            LinkedList<Book> lstempbook = temp.getCategory().listaLibros();
            for (int j = 0; j < lstempbook.getSize(); j++) {
                Book tempbr = lstempbook.getData();
                if (tempbr.getCarne_usuario_que_agrega() == actual_user.getNumero_carne() && tempbr.getTitulo().contains(keytyped)) {
                    Object[] tbl = {tempbr.getISBN(),
                        tempbr.getTitulo()
                    };
                    tabla.addRow(tbl);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarcaLibro;
    private javax.swing.JButton btnCrearLibro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBusqueda;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUsuario_agrega;
    // End of variables declaration//GEN-END:variables
}
