/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

import com.structures.*;

/**
 *
 * @author pedro
 */
public class Reporte extends javax.swing.JFrame {

    HashTable<User> usuarios;
    AVLTree arbol_categoria;
    WindowMain wm;

    /**
     * Creates new form Reporte
     *
     * @param usuarios
     * @param arbol_categoria
     * @param wm
     */
    public Reporte(HashTable<User> usuarios, AVLTree arbol_categoria, WindowMain wm) {
        this.wm = wm;
        this.usuarios = usuarios;
        this.arbol_categoria = arbol_categoria;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        fillCategories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAVL = new javax.swing.JButton();
        btnHashTable = new javax.swing.JButton();
        btnInOrder = new javax.swing.JButton();
        btnPostOrder = new javax.swing.JButton();
        btnPreOrder = new javax.swing.JButton();
        jcomboCategorias = new javax.swing.JComboBox<>();
        btnArbolB = new javax.swing.JButton();
        btnNodos = new javax.swing.JButton();
        btnBlockChain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpanelReporte = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnAVL.setText("AVL");
        btnAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAVLActionPerformed(evt);
            }
        });

        btnHashTable.setText("Tabla Hash");
        btnHashTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHashTableActionPerformed(evt);
            }
        });

        btnInOrder.setText("In Orden");
        btnInOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrderActionPerformed(evt);
            }
        });

        btnPostOrder.setText("Post Orden");
        btnPostOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostOrderActionPerformed(evt);
            }
        });

        btnPreOrder.setText("Pre Orden");
        btnPreOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrderActionPerformed(evt);
            }
        });

        btnArbolB.setText("Arbol B");
        btnArbolB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbolBActionPerformed(evt);
            }
        });

        btnNodos.setText("Nodos");

        btnBlockChain.setText("Blockchain");

        jLabel1.setText("REPORTE");

        jScrollPane2.setViewportView(jpanelReporte);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHashTable, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(btnAVL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPostOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPreOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcomboCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnArbolB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBlockChain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(454, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(328, 328, 328))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHashTable)
                        .addGap(35, 35, 35)
                        .addComponent(btnAVL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPostOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPreOrder)
                        .addGap(66, 66, 66)
                        .addComponent(btnArbolB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcomboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnNodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(btnBlockChain)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHashTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHashTableActionPerformed
        String url_image = usuarios.report();
        String content = "<img src=\"file:" + url_image + "\">";
        jpanelReporte.setContentType("text/html");
        jpanelReporte.setText(content);
    }//GEN-LAST:event_btnHashTableActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        wm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAVLActionPerformed
        String url_image = arbol_categoria.report();
        String content = "<img src=\"file:" + url_image + "\">";
        jpanelReporte.setContentType("text/html");
        jpanelReporte.setText(content);
    }//GEN-LAST:event_btnAVLActionPerformed

    private void btnInOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrderActionPerformed
        ReportList rl = new ReportList();
        String url_image = rl.reportelista(arbol_categoria.in_orden().getHead(), arbol_categoria.in_orden().getSize(), "InOrden");
        String content = "<img src=\"file:" + url_image + "\">";
        jpanelReporte.setContentType("text/html");
        jpanelReporte.setText(content);
    }//GEN-LAST:event_btnInOrderActionPerformed

    private void btnPostOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostOrderActionPerformed
        ReportList rl = new ReportList();
        String url_image = rl.reportelista(arbol_categoria.pos_order().getHead(), arbol_categoria.pos_order().getSize(), "PosOrden");
        String content = "<img src=\"file:" + url_image + "\">";
        jpanelReporte.setContentType("text/html");
        jpanelReporte.setText(content);
    }//GEN-LAST:event_btnPostOrderActionPerformed

    private void btnPreOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrderActionPerformed
        ReportList rl = new ReportList();
        String url_image = rl.reportelista(arbol_categoria.pre_order().getHead(), arbol_categoria.pre_order().getSize(), "PreOrden");
        String content = "<img src=\"file:" + url_image + "\">";
        jpanelReporte.setContentType("text/html");
        jpanelReporte.setText(content);
    }//GEN-LAST:event_btnPreOrderActionPerformed

    private void btnArbolBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbolBActionPerformed

    }//GEN-LAST:event_btnArbolBActionPerformed

    private void fillCategories() {
        jcomboCategorias.removeAllItems();
        LinkedList<BooksCategory> temp = arbol_categoria.in_orden();
        for (int i = 0; i < temp.getSize(); i++) {
            BooksCategory tmp = temp.getData();
            jcomboCategorias.addItem(tmp.getName_category());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAVL;
    private javax.swing.JButton btnArbolB;
    private javax.swing.JButton btnBlockChain;
    private javax.swing.JButton btnHashTable;
    private javax.swing.JButton btnInOrder;
    private javax.swing.JButton btnNodos;
    private javax.swing.JButton btnPostOrder;
    private javax.swing.JButton btnPreOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcomboCategorias;
    private javax.swing.JTextPane jpanelReporte;
    // End of variables declaration//GEN-END:variables
}
